
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etqymtvziglgcpvvrybj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0cXltdHZ6aWdsZ2NwdnZyeWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTI3NTYsImV4cCI6MjA1NTY4ODc1Nn0.duk53YH27_Va8EstZDRuqoMnKz2GiUvRWVJtrkVyw9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
